[package]
name = "look_up_table"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
itertools = "0.10.5"
cfg-if = "1.0.0"
heapless = {version="0.7.16", optional=true}
hashbrown = {version="0.14.0", optional=true}


[dev-dependencies]
rstest = "0.17.0"

[profile.release]
debug = false
lto = true
strip = true
panic="abort"
codegen-units=1
opt-level=3 # Although this option is to reduce size, this option sometimes increases the size

[features]
default = ["std"]
std = []
no-std = ["dep:heapless", "dep:hashbrown"]
