[package]
name = "look_up_table"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
itertools = "0.10.5"
heapless = "0.7.16"
hashbrown = "0.14.0"

[dev-dependencies]
rstest = "0.17.0"

